version: "3.8"
services:
  swagger:
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    ports:
      - 8011:8080
    environment:
      - SWAGGER_JSON=/tmp/openapi.yaml
    volumes:
      - ./../docu:/tmp

  database:
    image: mysql
    ports:
      - 9011:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8012:8080

volumes:
  mysql:
