version: "3.8"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  php-fpm:
    build:
      context: ./apps/core/docker/php-fpm
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}?serverVersion=8.0
      - JWT_PASSPHRASE=${JWT_PASSPHRASE}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - APP_PDF_LOGO=${APP_PDF_LOGO}
      - APP_PDF_FOOTER=${APP_PDF_FOOTER}
    volumes:
      - ./apps/core:/usr/local/apache2/htdocs
      - jwt:/usr/local/apache2/htdocs/config/jwt

  core:
    build:
      context: ./apps/core/docker/httpd
    restart: unless-stopped
    depends_on:
      - php-fpm
    ports:
      - ${PORT_CORE:-9001}:80
    volumes:
      - ./apps/core:/usr/local/apache2/htdocs

  kitchen:
    build:
      context: ./apps/kitchen
      args:
        - VUE_APP_API=${VUE_APP_API}
        - VUE_APP_I18N_LOCALE=${VUE_APP_I18N_LOCALE}
        - VUE_APP_BASE_URL=${VUE_APP_BASE_URL}
    restart: unless-stopped
    ports:
      - ${PORT_KITCHEN:-9002}:80

volumes:
  mysql:
  jwt: